language: python
python:
  - "3.7"
before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m  unittest discover -s  Tests